### ISSUE TITLE
Oplossing bedenken voor placeholder icm transparante png

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#100]
![afbeelding](https://user-images.githubusercontent.com/11227077/33829400-5e3714e6-de70-11e7-8bb9-2cd063a0bbe9.png)

Is natuurlijk niet zo heel erg mooi. Kan de placeholder niet ook een transparante png zijn? Dan is dat probleem met die blauwe balken onder images ook gelijk opgelost.

**Comment by hans2103** [comment]
<img width="362" alt="schermafdruk 2017-12-11 18 53 36" src="https://user-images.githubusercontent.com/639822/33845717-a066eb1e-dea4-11e7-81b7-3d616b7769fb.png">

**Comment by crommie** [comment]
Heb je nou het plaatje niet-transparant gemaakt @hans2103?

**Comment by hans2103** [comment]
ik heb het vimexx plaatje niet gewijzigd
ik heb alleen de afbeelding voor de placeholder (zwarte dingetje) gewijzigd naar een spacer.gif en de achtergondkleur blauw gewijzigd naar wit

**Comment by crommie** [comment]
Slim.
