### ISSUE TITLE
Layout pagina sponsors

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#11]

**Comment by dennisbuis** [comment]
<img width="2094" alt="jd17_6_ 2x_13" src="https://cloud.githubusercontent.com/assets/3339738/21004596/7a7cd21e-bd31-11e6-90cb-0a34029b009a.png">

**Comment by crommie** [comment]
Ja tof!


Op 8-12-2016 om 10:31 schreef Dennis Buis:

**Comment by hans2103** [comment]
Onder supporters heb ik een knop aangemaakt "Ja, ik wil ook Sponsor Supporter zijn!"
Met een link naar de supporter sponsor pagina in de shop

**Comment by hans2103** [comment]
@crommie aan jou en Hilda om de pagina van content te voorzien.

**Comment by crommie** [comment]
@hans2103 die knop zie ik in de site nog niet terug, heb je die per ongeluk lokaal gemaakt?

**Comment by crommie** [comment]
Content volgt, we zitten er bovenop. Zodra er ook maar iemand een handtekening zet zijn we er als de kippen bij.

**Comment by hans2103** [comment]
Was op de site ook gemaakt... alleen toegewezen aan de verkeerde pagina. Is nu gecorrigeerd. 
![schermafdruk 2016-12-12 19 25 25](https://cloud.githubusercontent.com/assets/639822/21111218/bf0a7d6a-c0a0-11e6-9792-612a58faf445.png)
