### ISSUE TITLE
Mediapagina: plek voor bedenken

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#13]
Zoals bij http://joomladagen.nl/mediapagina

Betere naam: "Zelf Joomla!Dagen promoten". Of zoiets.

**Comment by hans2103** [comment]
toegevoegd aan _Handige links_

**Comment by crommie** [comment]
@dennisbuis heb je ook nog een 468 x 60 bannertje?

**Comment by hans2103** [comment]
Label "Ready for testing" en Assignee "Anja de Crom" verwijderd, omdat het een issue is waar @dennisbuis iets voor moet doen momenteel.
