### ISSUE TITLE
Plaatjes voor mediapagina

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#14]
http://nieuw.joomladagen.nl/mediapagina

**Comment by dennisbuis** [comment]
Hi Anja,
ik hoor graag of dit zo naar wens is!

![joomla dagen_20178_banner_125x125px](https://cloud.githubusercontent.com/assets/3339738/21075680/5c316d4a-bf18-11e6-8b82-104de9492272.jpg)
![joomla dagen_20178_banner_250x250px](https://cloud.githubusercontent.com/assets/3339738/21075681/5c34e678-bf18-11e6-8079-c7284bfb50b5.jpg)

**Comment by hans2103** [comment]
![schermafdruk 2016-12-12 19 27 19](https://cloud.githubusercontent.com/assets/639822/21111276/03ea0a40-c0a1-11e6-84d5-240392b0d5a6.png)

Afbeeldingen zijn verwerkt zie ik. Er ontbreekt er nog eentje @dennisbuis 

gekopieerd vanuit #13 
> @dennisbuis heb je ook nog een 468 x 60 bannertje?

**Comment by dennisbuis** [comment]
@crommie deze ontbrak nog... ![afbeelding 468x60px](https://cloud.githubusercontent.com/assets/3339738/21161750/31575674-c18a-11e6-911a-450542313be1.jpg)

**Comment by sanderpotjer** [comment]
@dennisbuis heb je toevallig ook een 728x90 variant? (voor onder andere de nieuwe JC site)

**Comment by dennisbuis** [comment]
Toevallig wel ja... :-)
![joomla dagen 2017_ 728x90](https://cloud.githubusercontent.com/assets/3339738/21162024/94701f6a-c18b-11e6-8899-02c17f69c902.jpg)

**Comment by sanderpotjer** [comment]
Topper!

**Comment by hans2103** [comment]
@crommie verwerk jij de aangeleverde media?

**Comment by crommie** [comment]
done
