### ISSUE TITLE
Content sponsorpagina

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#18]
Introtekst met link naar Sponsor informatie (single article in sitemapmenu?)

@hans2103 wat vind jij?

**Comment by hans2103** [comment]
weergave sponsorpagina: https://projects.invisionapp.com/share/N49MVJ0JR#/screens

**Comment by hans2103** [comment]
mee eens.

**Comment by hans2103** [comment]
@crommie maak jij een correcte introtekst van de categorie Sponsoren?
http://nieuw.joomladagen.nl/administrator/index.php?option=com_categories&view=category&layout=edit&id=37&extension=com_content

**Comment by crommie** [comment]
Gedaan. Maar eigenwijs als ik ben heb ik er ook een link ingezet naar de sponsor informatie (menu voor sitemap -> sponsor informatie -> single article Sponsorpakketten 2017. 

Vinden we dat wat?

**Comment by hans2103** [comment]
index.php?option=com_content&amp;view=category&amp;layout=blog&amp;id=13&amp;Itemid=114
gewijzigd naar
/sponsors/informatie

want eerstgenoemde leverde een faal op
