### ISSUE TITLE
schrijfwijze Joomla!Dagen

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#21]
Joomladagen
Joomla!dagen
Joomla!Dagen
Joomla dagen
Joomla! dagen

welke schrijfwijze hanteren we?

**Comment by crommie** [comment]
Joomla!Dagen heb ik geleerd.

**Comment by roland-d** [comment]
@crommie Ik heb het nagevraagd en kreeg te horen JoomlaDagen met 1x een TM vermelding erbij. De documentatie is hier: https://docs.joomla.org/Joomla:Proper_use_of_the_Joomla!_name/nl

Sandra Thevenet zei het volgende:
For JoomlaDay, it's easy: JoomlaDay
Don't forget also that JoomlaDay is a trademark so the TM has to be placed once

**Comment by hans2103** [comment]
@crommie zou jij de juiste schrijfwijze door kunnen voeren in de content en Helix titels van menu items?

**Comment by crommie** [comment]
Volgens mij heb ik het overal aangepast nu. Met dank aan DB Replacer, want anders was het echt, echt niet te doen. Mocht je het nog ergens tegenkomen, let me know.
