### ISSUE TITLE
Te laag contrast text en afbeelding

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#22]
![schermafdruk 2016-12-12 08 55 53](https://cloud.githubusercontent.com/assets/639822/21091793/d1a9584a-c048-11e6-9cab-e0b84341c24d.png)

@dennisbuis heb jij hier een oplossing voor?

**Comment by dennisbuis** [comment]
afbeelding Donkerder, afbeelding donkerder en blurren;
![header_afbeelding_jdnl17_01](https://cloud.githubusercontent.com/assets/3339738/21157651/5c7b7c64-c17a-11e6-9a62-0ed8bfad2a56.jpg)
![header_afbeelding_jdnl17_02](https://cloud.githubusercontent.com/assets/3339738/21157652/5c7c0058-c17a-11e6-869b-e9318a28d272.jpg)

**Comment by hans2103** [comment]
afbeelding verwerkt

![schermafdruk 2016-12-14 10 10 05](https://cloud.githubusercontent.com/assets/639822/21176083/84ebe646-c1e5-11e6-980d-5446f0bc1833.png)
