### ISSUE TITLE
Programma - achtergrondkleur van tabelregels

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#24]
![schermafdruk 2016-12-12 09 00 19](https://cloud.githubusercontent.com/assets/639822/21091893/6ce54d0a-c049-11e6-87cd-6e63fad9780c.png)

De achtergrondkleuren van de tabellen zijn om en om wit en grijs. De algemene zaken, zoals pauze en lunch, zijn blauw. Daardoor rare overgang. 

Hoe moet het wel? Wat is je voorstel @dennisbuis

**Comment by dennisbuis** [comment]
Ik dacht dat idee was het het zelfde te stylen als op de oude site... mis nu dan alleen het kader eromheen, en de grijze kleur is wat te donker. Labels 'beginner' enz. kunnen ook overgenomen worden toch? alleen dan graag zonder border radius.

**Comment by hans2103** [comment]
Ik heb in deze ook de styling van de andere site overgenomen. Dit is het resultaat.
Op de border na... want die zit er in deze implementatie van de tabs niet omheen. 
Ik ga met de opmerkingen aan de slag.

**Comment by hans2103** [comment]
![schermafdruk 2016-12-14 10 45 12](https://cloud.githubusercontent.com/assets/639822/21177206/6ba750c6-c1ea-11e6-86b1-fdb3c1998834.png)
