### ISSUE TITLE
[Sitemap] Exclude pages

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#37]
@crommie kan jij pagina's gaan uitsluiten van de sitemap? Dit doe je via de afzonderlijke menu items

**Comment by crommie** [comment]
Ben ik zelf slim genoeg om te bedenken welke?

**Comment by hans2103** [comment]
@crommie ja hoor... jij bent slim genoeg om zelf te bedenken welke.

**Comment by crommie** [comment]
Toch niet. Moet nieuws erin?

**Comment by roland-d** [comment]
@crommie Ja, Nieuws moet erin
