### ISSUE TITLE
[Sponsors]

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#42]
![schermafdruk 2016-12-12 09 40 49](https://cloud.githubusercontent.com/assets/639822/21092859/189a9466-c04f-11e6-9f22-27a556e37702.png)

- [x] Toevoegen van social links en link naar site. 
- [x] Verwijder gelinkte titel

**Comment by roland-d** [comment]
@hans2103 Weet jij welk bestand dit is? Ik lijk het niet te kunnen vinden :-|

**Comment by hans2103** [comment]
@roland-d deze pagina is een category blog weergave. De social links zijn de items ingevuld bij tabblad _Afbeeldingen en Links_

**Comment by roland-d** [comment]
Deze pagina is nu aangepast en gecommit.

**Comment by hans2103** [comment]
ik zie het..top!
