### ISSUE TITLE
[Locatie] Als er geen image is...

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#43]
![afbeelding](https://cloud.githubusercontent.com/assets/11227077/21109016/8287eea8-c097-11e6-8adf-563b8b96b466.png)

**Comment by crommie** [comment]
Ik wil er ook gerust een plaatje van een trein neerzetten hoor :)

**Comment by hans2103** [comment]
oeps... dat was testcode... is nu weg

**Comment by crommie** [comment]
Cool. We zijn goed bezig.
