### ISSUE TITLE
Faal in plugin Social Meta Tags

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#44]
![schermafdruk 2016-12-12 19 30 51](https://cloud.githubusercontent.com/assets/639822/21111370/886349da-c0a1-11e6-8c63-0c067f8db994.png)

De maker is verzocht dit op te lossen. :-)

**Comment by hans2103** [comment]
Faal ontstaat door niet aanwezig zijn van basic image. 
issue #45 aangemaakt voor de aanlevering hiervan

**Comment by dennisbuis** [comment]
![500x500_2](https://cloud.githubusercontent.com/assets/3339738/21158855/36136244-c17f-11e6-926f-aceaa4dbebcb.jpg)

**Comment by hans2103** [comment]
vewerkt en foutmelding komt niet meer voor
