### ISSUE TITLE
Basic image 500x500 gewenst

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#45]
@dennisbuis kan jij een jd17nl afbeelding van 500x500 aanleveren?
Te gebruiken als basis afbeelding voor de Social Meta Tag plugin.

**Comment by dennisbuis** [comment]
![500x500_2](https://cloud.githubusercontent.com/assets/3339738/21158823/13561e2c-c17f-11e6-9186-eaa52cabc4c1.jpg)
zoiets?
