### ISSUE TITLE
Livegang

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#47]
Things to do bij livegang

- [x] cronjob path aanpassen naar live
- [x] release versie 1.0
- [x] set GTM
- [ ] Modules Supporters en Sponsor Supporter button module aanzetten als de shop live is

**Comment by hans2103** [comment]
@dennisbuis , @crommie en @roland-d 
Ter info: Zondagochtend 18 december zou ik de website nieuw.joomladagen.nl willen omzetten naar www.joomladagen.nl

**Comment by roland-d** [comment]
Klinkt goed @hans2103

**Comment by crommie** [comment]
Woehie! Spannend. Zeg, onze sponsordudette vraagt of in het topmenu toch niet ook een kopje Sponsors mag; ze worden nu een beetje weggemoffeld, is het gevoel.

**Comment by crommie** [comment]
Hoe laat? Moet ik standby zijn? Maandag gelijk een nieuwsbrief eroverheen knallen of liever een combi maken met opening ticketshop?

**Comment by crommie** [comment]
Als er nog geen ticketshop is, moet de knop in de headermodule misschien tijdelijk even uit?

![afbeelding](https://cloud.githubusercontent.com/assets/11227077/21288295/966ec1a8-c47f-11e6-8a1c-f0f7313a3508.png)
