### ISSUE TITLE
Sponsors naar topmenu?

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#48]
Zeg, onze sponsordudette vraagt of in het topmenu toch niet ook een kopje Sponsors mag; ze worden nu een beetje weggemoffeld, is het gevoel.

**Comment by hans2103** [comment]
Tijdens de eerste vergadering hebben we (@dennisbuis @crommie en @hans2103) besloten om het hoofdmenu speciaal te richten op de bezoekers van het event.
De onderdelen Home, Programma, Sprekers, Locatie en Tickets zijn daarbij als belangrijkste bepaald. De overige items zijn verplaatst naar het footermenu. 
We waren er ons toen ook van bewust dat het belangrijk is om sponsorgelden binnen te halen, maar dat de focus van de website ligt op de bezoeker, niet op de sponsor.

**Comment by crommie** [comment]
Ja, dat weet ik nog natuurlijk. Toelichting op de vraag: Hilda wil bij het bellen kunnen verwijzen naar de website, en dan is het tof voor een potentiële sponsor als-ie meteen op een menu-item kan klikken en niet eerst naar onderen moet scrollen. Maar ze gaat nu zeggen dat mensen /sponsors moeten intikken bij de url, en dus is het verder wel oké zoals het is.
