### ISSUE TITLE
Publicatiedatum?

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#49]
Ik zie dat bij alles nu de publicatiedatum vermeld wordt. Dat is niet altijd wenselijk (vooral niet als het een artikel uit 2012 is of zo). Zetten we dat per menu-item weer uit?

**Comment by hans2103** [comment]
Ik zou willen adviseren om bij alle nieuws items de datum actief te laten. Dat geeft de lezer direct informatie over het artikel. Als je niet wil dat je artikelen van oudere edities van de Joomladagen wil tonen, dan zou ik willen adviseren om het artikel te depubliceren.

**Comment by crommie** [comment]
Alleen bij nieuws dus. En op plekken zoals hier uitzetten lijkt me.

![afbeelding](https://cloud.githubusercontent.com/assets/11227077/21224873/898f348e-c2ce-11e6-99f9-6efd2d5eda17.png)

**Comment by hans2103** [comment]
@crommie op die plaatsen mag het zeker uit. Zou jij dit zelf bij de menu items kunnen instellen? Dan kan ik verder met shop

**Comment by crommie** [comment]
Ben al bezig :)

**Comment by crommie** [comment]
Hm. Algemene instellingen -> verberg. Toch staat-ie overal aan. Verbergen per menu-item werkt niet. Wordt het ergens overruled?

**Comment by hans2103** [comment]
@crommie ik heb de override aangepast, zodat nu ook de variabele meegenomen wordt om een datum uit te schakelen. zou je nogmaals kunnen testen?

**Comment by crommie** [comment]
Ik dacht al, er moet vast een if-je in. Volgens mij gaat het nu goed. Held!
