### ISSUE TITLE
Banners voor de sponsoren?

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#50]
Sponsordudette & ik bedachten dat het fenomeen "plaats een banner" natuurlijk net zo goed voor onze sponsoren geldt. Supertof als die ook banners op hun sites zetten.

@dennisbuis zou jij varianten van de media-pagina-banners kunnen maken met daarop Proud Sponsor en dan JoomlaDagen in Engelse en Nederlandse variant? Dan sturen wij die naar elke sponsor die getekend heeft :)

**Comment by dennisbuis** [comment]
![joomla dagen 2017_ 728x90 _proud sponsor](https://cloud.githubusercontent.com/assets/3339738/21820798/773865e6-d771-11e6-9f7b-b71265ed1247.png)
![joomla dagen 2017_ 728x90 _trotse sponsor](https://cloud.githubusercontent.com/assets/3339738/21820799/7739ca08-d771-11e6-9370-2e3b678e4f3f.png)
@crommie hier een op formaat 728x90, maar let op; ik maak ze met liefde op maat voor onze gewaardeerde sponsoren! Excuus dat zolang duurde...

**Comment by crommie** [comment]
Super Dennis! Gooi je ze even in Dropbox? Of heb je dat al gedaan? Dan 
vist Hilda ze er wel weer uit om ze naar onze gewaardeerde sponsoren te 
sturen.

Enne... twee vierkantjes zou ook fijn zijn, zelfde maten als de banners 
van de mediapagina.

Dank!


Op 10-1-2017 om 20:16 schreef Dennis Buis:

**Comment by dennisbuis** [comment]
f#ck 21 dagen geleden al weer...
Ik heb ze ook[ in dropbox gezet](https://www.dropbox.com/sh/dww64o0me02zikb/AADt8Y9SueIcEwYx_vMo4VORa?dl=0)... indien andere maten gewenst hoor ik dat graag.
![joomla dagen 2017_ 240x240 _kom je ook](https://cloud.githubusercontent.com/assets/3339738/22488260/42409f24-e811-11e6-8bde-38373237a7fb.png)
![joomla dagen 2017_ 240x240 _proudsponsor](https://cloud.githubusercontent.com/assets/3339738/22488262/4241e906-e811-11e6-90d3-6cc84479c2fd.png)
![joomla dagen 2017_ 240x240 _trotse sponsor](https://cloud.githubusercontent.com/assets/3339738/22488259/423cd10a-e811-11e6-9ebb-4a47d6a9b866.png)
