### ISSUE TITLE
Paginanavigatie

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#53]
Links vorige volgende missen chevron en zijn allebei nog plat en links aangelijnd

![afbeelding](https://cloud.githubusercontent.com/assets/11227077/21285680/ce624444-c43f-11e6-89a4-7934d9013f60.png)

http://nieuw.joomladagen.nl/nieuws/interviews/agnes-het-weekend-eindigt-altijd-veel-te-snel

**Comment by roland-d** [comment]
@crommie De interview pagina's zijn aangepast. Er zit nu styling op de links en ze zijn naar beneden verplaatst.

Als je weer een interview plaatst moet je bij het bewerken van het artikel op het tabblad Opties de alternatieve weergave **interview** kiezen:

![image](https://cloud.githubusercontent.com/assets/359377/21295350/7f8f6b02-c553-11e6-804e-657cc1ee3126.png)
