### ISSUE TITLE
Extra moduleblokje

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#55]
@hans2103 kunnen we nog één extra moduleblok toevoegen voor de module "Ook naar de JoomlaDagen"? Module is er al (custom html), is een simpel zinnetje met Call to Action button naar de ticketshop. Dan kunnen we die simpelweg aan en uit zetten afhankelijk van of er tickets zijn.

Positie: onder de tekst, boven de sponsorblokken.

Ik zag dat er een modulepositie content-below bestaat (maar niet actief is, denk ik), daar heb ik 'm nu even in gezet maar als jij aangeeft waar hij in moet komen zet ik 'm daarin.

**Comment by hans2103** [comment]
ik zal dit na de livegang onderzoeken

**Comment by hans2103** [comment]
modulepositie aangemaakt en zichtbaar op de pagina. 
@crommie Bij akkoord kan dit issue gesloten worden.
