### ISSUE TITLE
"Interesse in deze sponsorplek" -> gaat naar 404

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#57]
De link achter de plaatjes 'Interesse in deze sponsorplek" gaat naar een 404 pagina. Ik zou verwachten dat het gaat naar pagina met sponsor informatie.

**Comment by crommie** [comment]
Hij gaat naar sponsors/sponsor-informatie en die link heet tegenwoordig sponsors/informatie. Wat zal ik doen: het menu-item hernoemen (wat doet dat voor de sitemap?) OF het menu-item dezelfde naam laten houden en de links aanpassen?

**Comment by hans2103** [comment]
gezien... en het werkt.
