### ISSUE TITLE
Sponsorpakketten tabs diamant valt eraf

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#58]
![afbeelding](https://cloud.githubusercontent.com/assets/11227077/21293108/f08b4f12-c51a-11e6-8054-39660f90e628.png)

**Comment by hans2103** [comment]
De menuitem parameter "fulltext image" moet voor deze pagina op "No" gezet worden.
Dat heb ik bij deze gedaan.

**Comment by crommie** [comment]
Top top top
