### ISSUE TITLE
Styling vorige en volgende linkjes

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/joomladagen.nl#62]
@hans2103 @dennisbuis Op deze pagina, http://joomladagen.nl/nieuws/interviews/agnes-het-weekend-eindigt-altijd-veel-te-snel zijn de Vorige en Volgende niet gestyled:

![image](https://cloud.githubusercontent.com/assets/359377/21294715/f691c0e8-c543-11e6-8cf4-10d3e0f8f833.png)

Als iemand mij kan laten weten hoe ze eruit moeten komen te zien kan ik het wellicht aanpassen.

**Comment by roland-d** [comment]
Duplicaat van #53

**Comment by dennisbuis** [comment]
Wat mij betreft kunnen deze onder het artikel, en dat met de styling zoals bijgevoegde afbeelding. 
Styling:  btn--ghost--inverse

**Comment by roland-d** [comment]
Dat gaat me nog wel lukken :)

**Comment by roland-d** [comment]
@dennisbuis Styling staat erop en paginering onderaan.
