### ISSUE TITLE
OSM Disclaimer in het Engels nodig

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/joomladagen.nl#65]
De aanmelding van de joomladagen.nl site op de Joomla events pagina is afgekeurd vanwege de volgende reden:
The event site should show the OSM disclaimer text in all the pages in English and you may also include it in Dutch if you want. We usually suggest to include it in the footer position of the template.

Kan deze toegevoegd worden?

**Comment by sanderpotjer** [comment]
@roland-d wellicht even informeren waar het in de Joomla regels staat dat het op elke pagina moet? Heb dat zelf niet kunnen vinden. Staat wel al op https://www.joomladagen.nl/disclaimer

**Comment by sanderpotjer** [comment]
(al hebben alle goedgekeurde events het wel idd)

**Comment by roland-d** [comment]
@sanderpotjer Ik heb het nagevraagd. Hier kom ik op terug.

**Comment by roland-d** [comment]
@sanderpotjer Ik heb een reactie. Hier staat het een en ander:
https://tm.joomla.org/trademark-policy
https://tm.joomla.org/disclaimers#JoomlaDays

Carlos geeft ook aan dat hij het mis had ;) De disclaimer in beide talen hoeft alleen op de voorpagina zoals vermeld in de trademark policy.

**Comment by sanderpotjer** [comment]
@roland-d dank! Ik had destijds zitten zoeken in de JoomlaDay info, maar niet bij TM gekeken.. Merci!

**Comment by hans2103** [comment]
Dju... ik had alleen de pagina disclaimer gelezen en niet trademark. Uit pagina disclaimer maak ik namelijk niet op dat het niet toegestaan is om alleen de pagina https://www.joomladagen.nl/disclaimer te gebruiken. 
Uit pagina /trademark-policy maak ik wel op dat het op de home page aanbevolen wordt de disclaimer informatie te tonen. 

Ik zal onderaan het lichtblauwe blok de door de Joomla! (https://tm.joomla.org/disclaimers#JoomlaDays) aangeboden disclaimer plaatsen in witte tekst.

**Comment by crommie** [comment]
En ik had natuurlijk braaf opgevolgd wat Hans gezegd had :). Maar nu is 
het dus gefikst? Of zo goed als?


Op 3-1-2017 om 12:09 schreef Hans Kuijpers:

**Comment by hans2103** [comment]
De disclaimer staat nu onderaan op elke pagina van de website www.joomladagen.nl
