### ISSUE TITLE
Tot wanneer is early bird

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomladagen.nl#70]
Op homepage wordt het niet duidelijk tot wanneer de early bird loopt, denk goed om te melden + hoeveel korting je dan krijgt door nu je kaarten te kopen

**Comment by crommie** [comment]
@hans2103 moet dat geen € 25 zijn ipv 25%? 100 en 75 is wel 25%, maar 145 en 120 niet.

**Comment by hans2103** [comment]
done... (het was ooit begonnen als zijnde 25%. maar 25 euro past nu beter. dank je)
![schermafdruk 2017-01-31 16 48 29](https://cloud.githubusercontent.com/assets/639822/22472172/1e78871e-e7d5-11e6-90e4-5b74a7d872a3.png)
