### ISSUE TITLE
Nog een dirty hack nodig voor R2H zaal

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#72]
Deze is goed

![afbeelding](https://cloud.githubusercontent.com/assets/11227077/23299380/b56c01f0-fa81-11e6-841e-c116e1b3e4bd.png)

Deze nog niet

![afbeelding](https://cloud.githubusercontent.com/assets/11227077/23299422/d013e55e-fa81-11e6-964e-c7523a810aa3.png)

**Comment by hans2103** [comment]
Heb je voor mij de url van "deze"?
Dan kijk ik daar volgende week na de carnaval naar.

**Comment by crommie** [comment]
Tuurlijk! De goeie: https://www.joomladagen.nl/programma

De nog niet goeie: https://www.joomladagen.nl/presentaties/joomla-certificeringsprogramma-examen

En ik weet niet of Bugs Squashen ook een officieel programma-onderdeel moet worden, misschien moeten we dat even met Roland afstemmen, maar dan moet die ook. Dan weten we dat maar vast.

Agge mar leut et. Zeggen ze bij ons in Bergen op Zoom, al sinds 11-11 :)
