### ISSUE TITLE
sponsor & vrijwilligers pagina

### ISSUE THREAD

**Issue by fonnysmets** [stichtingsympathy/joomladagen.nl#75]
sponsor pagina voorlopig weg of melden dat dit de 2017 sponsors waren

ruimte tussen sponsornaam en teksten
underscore vind ik niet mooi

idem voor de vrijwilligerspagina

hansie doet het vele werk van de website wel maar moet die nu echt zo groot? ;-)

**Comment by hans2103** [comment]
@fonnysmets hoe groot? KUn je een screenshot plaatsen?

**Comment by fonnysmets** [comment]
groot genoeg?  ;-) ;-)



Met vriendelijke groeten

Fonny

**Comment by hans2103** [comment]
<img width="790" alt="schermafdruk 2017-11-18 14 24 18" src="https://user-images.githubusercontent.com/639822/32980718-3227580e-cc6c-11e7-8205-0ce952dc71e0.png">
dit is hetgeen ik in Github zie

**Comment by hans2103** [comment]
Ik heb het plaatje gezien en opgelost. 
<img width="562" alt="schermafdruk 2017-11-20 00 16 50" src="https://user-images.githubusercontent.com/639822/32996805-1dbfb40c-cd88-11e7-8d16-8fba253ac5db.png">

**Comment by fonnysmets** [comment]
ok, looks nicer
