### ISSUE TITLE
teller doet het niet

### ISSUE THREAD

**Issue by fonnysmets** [stichtingsympathy/joomladagen.nl#79]

**Comment by SpiritJC** [comment]
De teller (dagen/uren etc) werkt niet in Safari. In chrome en firefox werkt de teller.

**Comment by hans2103** [comment]
De teller werkte bij mij op desktop dikke prima. Op iPhone werkte het bij mij ook niet.
Maar het is nu opgelost.. bij mij is het opgelost Chrome iPhone en Safari iPhone.

**Comment by fonnysmets** [comment]
doet het bij mij nu ook
