### ISSUE TITLE
[footer balk] tekst 'Over Joomladagen" wijzigen

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#8]
@crommie zou jij de tekst "Over Joomladagen" kunnen wijzigen naar iets tofs enzo?

**Comment by crommie** [comment]
Sure.

**Comment by crommie** [comment]
Oké er is iets redelijk tofs. Kunnen we er een linkje naar Sympathy in bakken, dat mensen naar wat extra tekst kunnen (woho, misschien met een modal, dat zou gaaf zijn)? Want ik heb Sympathy er nu uit gesloopt maar er moet wel ergens wat aandacht voor zijn. Of in de footer-disclaimer-colofon-whatever, als het maar wel ergens is.

**Comment by hans2103** [comment]
ja hoor... ga je gang.

**Comment by crommie** [comment]
Na de vakantie :)
