### ISSUE TITLE
vrijdag: daarom joomla salespitch

### ISSUE THREAD

**Issue by fonnysmets** [stichtingsympathy/joomladagen.nl#81]
de doelgroep voor vrijdag wordt niet echt omschreven. 

We beginnen met 'het event voor de website bouwers'. Daardoor wordt een een deel van de doelgroep die we vrijdag willen bereiken al uitgesloten, nl diegenen die nog niet met Joomla werken en diegenen die niet techneut/technisch zijn.

Kunnen we niet beter omschrijven als: hét jaarlijkse event voor iedereen die meer wil weten waarom Joomla het onmisbare instrument is om jou website te bouwen. Maak kennis met Joomla en leer over ervaringen van andere gebruikers tijdens de presentaties of volg als (ver)gevorderde contentbeheerder of ontwikkelaar één van de verschillende workshops.

**Comment by hans2103** [comment]
@crommie pak jij dit op door wijziging van de content in de module?

**Comment by crommie** [comment]
Ja hoor. @fonnysmets, jij zegt "de doelgroep wordt niet echt omschreven", maar in je suggestie volsta je met "iedereen die meer wil weten", is dat dan wel voldoende omschreven? Of moeten er nog subgroepen benoemd worden zoals contentbeheerder, redacteur, vormgever, ehm... ? Dan graag extra input.

**Comment by fonnysmets** [comment]
Ik denk dat belangrijkste is dat we het ‘presentatie’ gedeelte op vrijdag duidelijk omschrijven dat dit voor niet-techneuten is, voor diegenen die Joomla niet kennen en er meer willen van weten, zoals it-ers op zoek naar een oplossing voor hun web-behoeftes, grafische bureau’s op zoek naar een krachtig web-ontwikkelplatform voor hun klanten, webdesigners op zoek naar een moduleerbare oplossing, ...
Maw een duidelijk signaal naar de markt dat we hier een andere (en nieuwe) groep van geïnteresseerden willen bereiken die op zoek zijn naar een krachtig web-ontwikkelplatform dat voldoet aan alle security normen, gebruikersinterface, … Het is DAAROM dat Joomla weerom als beste CMS systeem ter wereld verkozen is !

DAAROM dat we jou ook graag willen laten kennis maken met dit krachtig systeem en jou in een heldere taal graag alle mogelijkheden willen presenteren waarom Joomla JOU web oplossing kan aanbieden. Om dit nog kracht bij te zetten zullen een aantal bedrijven graag hun ervaring met JOU willen delen waarom zij voor Joomla gekozen hebben.


Zoiets in die stijl ?

**Comment by crommie** [comment]
@fonnysmets maar dat gaan we natuurlijk niet op de voorpagina doen, want dat is wel heel veel tekst. Wil je even kijken naar wat er nu staat?

**Comment by fonnysmets** [comment]
Ja, is al beter.
Hopelijk komt er een doorklik pagina waarop dan later duidelijk de context omschreven wordt.



Met vriendelijke groeten

Fonny

**Comment by crommie** [comment]
Ik neem aan dat het voor nu goed genoeg is en sluit deze issue.
