### ISSUE TITLE
pagina sponsorinformatie

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#84]
Artikel Sponsorpakketten 2018 is aangemaakt obv artikel vorig jaar. Pagina kan opgemaakt worden.

Links "bestel dit pakketje in de ticketshop" zijn eruit, moeten opnieuw aangemaakt worden zodra ticketshop live is.

**Comment by hans2103** [comment]
@crommie wat is de url van die pagina?

**Comment by crommie** [comment]
https://www.joomladagen.nl/sponsors/sponsor-informatie

**Comment by hans2103** [comment]
@crommie hoe wil Hilda dat deze pagina opgemaakt gaat worden?
Heeft ze voorbeelden van sites waar het naar wens uit ziet?

**Comment by hans2103** [comment]
https://www.joomladagen.nl/sponsors/sponsor-informatie
voorzien van tabs

**Comment by crommie** [comment]
Mooi @hans2103
