### ISSUE TITLE
weergave contacten wijzigen

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomladagen.nl#85]
https://www.joomladagen.nl/contact/4-hilda-abbing

de weergave van een contact moet nog gestyled worden.
<img width="859" alt="schermafdruk 2017-11-21 01 10 51" src="https://user-images.githubusercontent.com/639822/33047988-e06b32ee-ce58-11e7-8c05-338611196291.png">

**Comment by hans2103** [comment]
https://www.joomladagen.nl/sponsors/sponsor-informatie/aanvragen
formulier aangepast

**Comment by crommie** [comment]
Alle links naar dit contactformulier zijn aangepast.
