### ISSUE TITLE
pagina locatie

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#86]
Tekst is ook al een tijdje klaar: https://www.joomladagen.nl/locatie

**Comment by hans2103** [comment]
menu item type gewijzigd van category-blog naar individueel artikel

![schermafdruk 2017-11-21 15 02 50](https://user-images.githubusercontent.com/639822/33076459-13f8f168-cecd-11e7-91a5-813164bc70b8.png)

**Comment by crommie** [comment]
Foto geeft nog een blauw vlak eronder. Instellen op liggende foto @hans2103 

Google Maps eronder? Lijkt mij wel logisch :)

**Comment by crommie** [comment]
Pagina is nu goed, ik maak een nieuw issue van Google Maps blok
