### ISSUE TITLE
module nieuws op home

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#89]
Drie blokjes naast elkaar: twee blokjes met nieuwsartikelen, eentje met interview.

Uit het ontwerp van Dennis zijn ze eruit gevallen dus we mogen zelf weten waar ze komen :)

**Comment by crommie** [comment]
tekeningetje maken en dan kan Hans ermee aan de slag

**Comment by hans2103** [comment]
duplicate met #93
