### ISSUE TITLE
padding module Over de Joomladagen op home

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#90]
![afbeelding](https://user-images.githubusercontent.com/11227077/33093238-c0479d32-cefc-11e7-8ca2-1d3a7725cf9a.png)

Lillek!

**Comment by hans2103** [comment]
![schermafdruk 2017-11-22 11 35 12](https://user-images.githubusercontent.com/639822/33123030-3af42e3e-cf79-11e7-92c9-eb220fd05614.png)
