### ISSUE TITLE
module Vrijdag: Daarom Joomla is verzakt

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#94]
@hans2103 het was een ongelukje! Echt waar! Weet jij hoe we het weer kunnen fiksen?

![afbeelding](https://user-images.githubusercontent.com/11227077/33183100-cbde8586-d076-11e7-88ae-836b7213d71b.png)

**Comment by hans2103** [comment]
module was verzakt omdat de _Alternatieve weergave_ van mod_custom gewijzigd was van _clean_ naar _default_. Daardoor wordt er meer code en dus ook styling ingeladen dan nodig is.

**Comment by hans2103** [comment]
Is nu weer in orde

**Comment by crommie** [comment]
Euj. Maar dát had ik niet gedaan.
