### ISSUE TITLE
blokje voor videoteaser op home

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#95]
Onder vrijdag/zaterdag, boven de nieuwsblokjes.

**Comment by hans2103** [comment]
@crommie wat is de link naar youtube?

**Comment by crommie** [comment]
https://www.youtube.com/watch?v=Xe4fcNRjP_Q

**Comment by crommie** [comment]
gooi jij m erin @hans2103?

**Comment by hans2103** [comment]
@crommie de video is verwerkt op de site

**Comment by crommie** [comment]
Mooi @hans2103
