### ISSUE TITLE
aanvraag sponsorinformatie stylen + menu-item voor maken

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#96]
![afbeelding](https://user-images.githubusercontent.com/11227077/33663397-12e21466-da90-11e7-9bd1-d7f4aef3c810.png)

Mag nog best een bietje mooier: juiste header bijvoorbeeld etc. 
Koppelen we het formulier aan een menu-item? Backend -> juiste formulier -> Hulpmiddelen -> Voeg toe aan menu.

De contactlink bij de sponsorinfo gaat nu nog naar het oude contactformulier. Die links moeten ook aangepast worden (want 404), en het fijnst is het natuurlijk als dat met een interne menulink kan. Vandaar.

**Comment by hans2103** [comment]
<img width="1626" alt="schermafdruk 2017-12-07 00 32 29" src="https://user-images.githubusercontent.com/639822/33690945-225b79ea-dae6-11e7-8d8e-10e2f561fbec.png">
Dit is hetgeen ik zie en wijkt af met hetgeen jij ziet.
https://www.joomladagen.nl/sponsors/sponsor-informatie/aanvragen

Het formulier is op desktop inderdaad nogal breed.
Ik zal hem smaller maken.

**Comment by hans2103** [comment]
Op schermbreedte delta (768px) zal het formulier 50% zijn van de .container

<img width="1626" alt="schermafdruk 2017-12-07 00 42 20" src="https://user-images.githubusercontent.com/639822/33691223-81a87280-dae7-11e7-9f38-182c8c394942.png">

**Comment by crommie** [comment]
Mooi Hans.
