### ISSUE TITLE
Pagina organisatie styling plaatjes; daarna link weer activeren

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomladagen.nl#98]
![afbeelding](https://user-images.githubusercontent.com/11227077/33762920-c45885f2-dc0e-11e7-9d0d-2ecfe64ca391.png)

@hans2103 Moeten we er nieuwe plaatjes in zetten die wel passen? Of iets anders doen?

**Comment by hans2103** [comment]
Hier moeten we de plaatjes opnieuw toewijzen, zodat ze netjes afgesneden worden naar 1:1

**Comment by crommie** [comment]
Opnieuw toewijzen betekent? Artikel openen, plaatje erin zetten, artikel sluiten? Of volstaat openen en sluiten? Anders uploaden, dat betekent eerst downloaden want ik weet niet hoe het met jou zit, maar ik heb geen foto van Fonny op mijn lokale computer staan :)

**Comment by hans2103** [comment]
dunno... dat zal ik zelf even moeten testen.

**Comment by hans2103** [comment]
@crommie vind je dat dit issue met oplossing voor #100 ook opgelost is?

**Comment by crommie** [comment]
Hij ziet er top uit zo. Dus ik vind het goed @hans2103
